# Jekyll config
markdown: kramdown
sass:
  sass_dir: assets/_sass
collections:
  projects:
    output: true
    sort_by: order
    permalink: /:collection/:name
  pages:
    output: true
    sort_by: order
    permalink: /:title
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom
social:
  instagram:
    url: https://instagram.com/jennifergardnerofficial/
    username: jennifergardnerofficial
